
n_groups: 2
replicates: 3

# number of transcripts to sample
n_transcripts:
  n: 20000
  seed: 11

fold_changes:
  seed: 12

simulate_experiment:
  effects: [0.5, 1, 2]
  probs: [0.05, 0.9, 0.05]
  seed: 13

contrasts:
  group1-vs-group2:
    - 1
    - 2
